# Generated by Django 6.1.1 on 2026-09-30 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('kind', models.CharField(choices=[('ingredient', 'Ingredient'), ('finished', 'Finished good')], max_length=20)),
                ('stock', models.PositiveIntegerField(default=0, help_text='Stock on hand')),
            ],
            options={
                'ordering': ['kind', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ManufacturingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='How many units to produce')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('done', 'Done')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('produced_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(limit_choices_to={'kind': 'finished'}, on_delete=django.db.models.deletion.PROTECT, related_name='manufacturing_orders', to='factory.product')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='mo_quantity_positive')],
            },
        ),
        migrations.CreateModel(
            name='BomLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='Amount of ingredient per 1 unit of product')),
                ('ingredient', models.ForeignKey(limit_choices_to={'kind': 'ingredient'}, on_delete=django.db.models.deletion.PROTECT, related_name='used_in', to='factory.product')),
                ('product', models.ForeignKey(limit_choices_to={'kind': 'finished'}, on_delete=django.db.models.deletion.CASCADE, related_name='bom_lines', to='factory.product')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('product', 'ingredient'), name='unique_ingredient_per_product'), models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='bom_quantity_positive')],
            },
        ),
    ]
