# Generated by Django 6.1.1 on 2026-10-02 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0002_stockmovement'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Untick = product was removed (kept for history)'),
        ),
        migrations.AlterField(
            model_name='manufacturingorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='reason',
            field=models.CharField(choices=[('restock', 'Restock'), ('consumed', 'Used in production'), ('produced', 'Produced'), ('imported', 'Imported (finished goods)'), ('written_off', 'Written off (product removed)')], max_length=20),
        ),
    ]
